#!/usr/bin/env bash

# TODO: Make a script to download youtube video from given timeframes
#
# E.g.: youtube-time 2:00 4:00 tutorial.mkv "https://www.youtube.com/watch?v=SPwyp2NG-bE"
# The above command should create a output file which contains the video from 2 min to 4 min.
#
# Refer: youtube-dl and ffmpeg commands for this

#!/bin/bash

echo "Enter the path of the video file: "
read input_file

echo "Enter start time (in the formatHH:MM:SS): "
read start_time

echo "Enter end time (int the format HH:MM:SS): "
read end_time

echo "Enter output file name (with extension): "
read output_file

# Extract the required segment
echo "Extracting segment..."
ffmpeg -ss "$start_time" -i "$input_file" -to "$end_time" -c copy "$output_file"

echo "Segment saved as $output_file"



